#!/bin/bash
# CLI Setup Script for harness_coding_instructions
# Generates entry-point files for CLI tools (Claude Code, Codex)
# and ensures repo_info/ structure exists.
#
# Run this script from the root of your target repo AFTER copying
# harness_coding_instructions into .github/harness_coding_instructions/

set -e

PACK_DIR=".github/harness_coding_instructions"

if [ ! -d "$PACK_DIR" ]; then
    echo "Error: $PACK_DIR not found." >&2
    echo "Run this script from the target repo root after copying the pack to $PACK_DIR/." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Detect which CLI tools are installed
# ---------------------------------------------------------------------------
HAS_CLAUDE=false
HAS_CODEX=false

if command -v claude >/dev/null 2>&1; then
    HAS_CLAUDE=true
    echo "Detected: Claude Code CLI"
fi

if command -v codex >/dev/null 2>&1; then
    HAS_CODEX=true
    echo "Detected: Codex CLI"
fi

if [ "$HAS_CLAUDE" = false ] && [ "$HAS_CODEX" = false ]; then
    echo "No CLI tools detected (claude, codex). Generating both entry points anyway."
fi

install_generated_file() {
    local src="$1"
    local dest="$2"
    local marker="$3"
    local label="$4"

    if [ ! -f "$src" ]; then
        echo "$label not found in pack — skipping generation."
        return
    fi

    if [ ! -f "$dest" ]; then
        cp "$src" "$dest"
        echo "Created $dest ($label)"
    elif [ -n "$marker" ] && grep -Fq "$marker" "$dest"; then
        cp "$src" "$dest"
        echo "Refreshed generated $dest ($label)"
    else
        echo "WARNING: $dest exists and does not look generated by this pack — leaving it unchanged." >&2
    fi
}

# ---------------------------------------------------------------------------
# 2. Generate CLAUDE.md at repo root (for Claude Code CLI)
# ---------------------------------------------------------------------------
install_generated_file "$PACK_DIR/CLAUDE.md" "CLAUDE.md" "Claude Code CLI Entry Point" "Claude Code entry point"

# ---------------------------------------------------------------------------
# 3. Generate AGENTS.md at repo root (for Codex CLI)
# ---------------------------------------------------------------------------
install_generated_file "$PACK_DIR/AGENTS.md" "AGENTS.md" "Codex CLI Entry Point" "Codex entry point"

# ---------------------------------------------------------------------------
# 4. Copy copilot-instructions.md to .github/ (standard Copilot discovery path)
# ---------------------------------------------------------------------------
if [ -f "$PACK_DIR/copilot-instructions.md" ]; then
    mkdir -p ".github"
    COPILOT_DEST=".github/copilot-instructions.md"
    if [ ! -f "$COPILOT_DEST" ]; then
        sed 's|#file:|#file:harness_coding_instructions/|g' "$PACK_DIR/copilot-instructions.md" > "$COPILOT_DEST"
        echo "Created $COPILOT_DEST (GitHub Copilot instructions)"
    elif grep -Fq "Master Orchestrator — Instruction Router" "$COPILOT_DEST"; then
        sed 's|#file:|#file:harness_coding_instructions/|g' "$PACK_DIR/copilot-instructions.md" > "$COPILOT_DEST"
        echo "Refreshed $COPILOT_DEST (GitHub Copilot instructions)"
    else
        echo "WARNING: $COPILOT_DEST exists with custom content — leaving unchanged." >&2
    fi
fi

# ---------------------------------------------------------------------------
# 5. Copy .claude/rules/ directory if provided by the pack
# ---------------------------------------------------------------------------
if [ -d "$PACK_DIR/.claude/rules" ]; then
    mkdir -p ".claude/rules"
    for rule_file in "$PACK_DIR/.claude/rules/"*.md; do
        [ -f "$rule_file" ] || continue
        rule_name=$(basename "$rule_file")
        rule_marker=$(awk '/^# / { print; exit }' "$rule_file")
        install_generated_file "$rule_file" ".claude/rules/$rule_name" "$rule_marker" "Claude Code rule $rule_name"
    done
fi

# ---------------------------------------------------------------------------
# 6. Ensure repo_info/ folder exists with all canonical files
# ---------------------------------------------------------------------------
REPO_INFO="$PACK_DIR/repo_info"
mkdir -p "$REPO_INFO"

CANONICAL_FILES=(
    "codebase_overview.md"
    "scripts_overview.md"
    "update_logs.md"
    "known_issues.md"
    "update_logs_auto_generated.md"
    "known_issues_auto_generated.md"
    "past_Q&A.md"
    "past_Correctness_Check.md"
)

for f in "${CANONICAL_FILES[@]}"; do
    if [ ! -f "$REPO_INFO/$f" ]; then
        touch "$REPO_INFO/$f"
        echo "Created $REPO_INFO/$f"
    fi
done

echo ""
echo "CLI setup complete."
echo ""
echo "Usage:"
if [ "$HAS_CLAUDE" = true ]; then
    echo "  Claude Code: Run 'claude' from repo root — it discovers CLAUDE.md automatically"
fi
if [ "$HAS_CODEX" = true ]; then
    echo "  Codex:       Run 'codex' from repo root — it discovers AGENTS.md automatically"
fi

# --- Agent Discovery Guidance ---
echo ""
echo "=== Agent Discovery ==="
echo "Agent definitions are at: .github/harness_coding_instructions/agents/"
echo ""
echo "For Claude Code:"
echo "  Subagents are spawned via the Task tool with inline prompts."
echo "  CLAUDE.md routes to workflow files which reference agent definitions"
echo "  by name. No additional agent directory configuration is needed."
echo ""
echo "For Codex CLI:"
echo "  AGENTS.md routes to workflow files which reference agent definitions"
echo "  by name. Subagents are spawned as Codex agent workers."
echo "  Use 'mode: fast' in a prompt to select workflow/codex_token_effective_workflow/."
echo "  If subagent spawning fails, ensure your Codex concurrency settings"
echo "  allow multiple agent workers."
echo ""

echo "Next step: Run the initialize workflow to generate repo_info/ memory files."
echo "Done."
