#!/bin/bash
# CLI Setup Script for HarnessFlow
# Generates entry-point files for CLI tools (Claude Code, Codex)
# and ensures repo_info/ structure exists.
#
# Run this script from the root of your target repo AFTER copying
# HarnessFlow into .github/HarnessFlow/

set -e

PACK_DIR=".github/HarnessFlow"

if [ ! -d "$PACK_DIR" ]; then
    echo "Error: $PACK_DIR not found." >&2
    echo "Run this script from the target repo root after copying the pack to $PACK_DIR/." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Detect which CLI tools are installed
# ---------------------------------------------------------------------------
HAS_CLAUDE=false
HAS_CODEX=false

if command -v claude >/dev/null 2>&1; then
    HAS_CLAUDE=true
    echo "Detected: Claude Code CLI"
fi

if command -v codex >/dev/null 2>&1; then
    HAS_CODEX=true
    echo "Detected: Codex CLI"
fi

if [ "$HAS_CLAUDE" = false ] && [ "$HAS_CODEX" = false ]; then
    echo "No CLI tools detected (claude, codex). Generating both entry points anyway."
fi

install_generated_file() {
    local src="$1"
    local dest="$2"
    local marker="$3"
    local label="$4"

    if [ ! -f "$src" ]; then
        echo "$label not found in pack — skipping generation."
        return
    fi

    if [ ! -f "$dest" ]; then
        cp "$src" "$dest"
        echo "Created $dest ($label)"
    elif [ -n "$marker" ] && grep -Fq "$marker" "$dest"; then
        cp "$src" "$dest"
        echo "Refreshed generated $dest ($label)"
    else
        echo "WARNING: $dest exists and does not look generated by this pack — leaving it unchanged." >&2
    fi
}

# ---------------------------------------------------------------------------
# 2. Generate CLAUDE.md at repo root (for Claude Code CLI)
# ---------------------------------------------------------------------------
install_generated_file "$PACK_DIR/CLAUDE.md" "CLAUDE.md" "Claude Code CLI Entry Point" "Claude Code entry point"

# ---------------------------------------------------------------------------
# 3. Generate AGENTS.md at repo root (for Codex CLI)
# ---------------------------------------------------------------------------
install_generated_file "$PACK_DIR/AGENTS.md" "AGENTS.md" "AGENTS.md — Codex" "Codex entry point"

# ---------------------------------------------------------------------------
# 4. Copy copilot-instructions.md to .github/ (standard Copilot discovery path)
# ---------------------------------------------------------------------------
if [ -f "$PACK_DIR/copilot-instructions.md" ]; then
    mkdir -p ".github"
    COPILOT_DEST=".github/copilot-instructions.md"
    if [ ! -f "$COPILOT_DEST" ]; then
        sed 's|#file:|#file:HarnessFlow/|g' "$PACK_DIR/copilot-instructions.md" > "$COPILOT_DEST"
        echo "Created $COPILOT_DEST (GitHub Copilot instructions)"
    elif grep -Fq "Master Orchestrator" "$COPILOT_DEST"; then
        sed 's|#file:|#file:HarnessFlow/|g' "$PACK_DIR/copilot-instructions.md" > "$COPILOT_DEST"
        echo "Refreshed $COPILOT_DEST (GitHub Copilot instructions)"
    else
        echo "WARNING: $COPILOT_DEST exists with custom content — leaving unchanged." >&2
    fi
fi

# ---------------------------------------------------------------------------
# 5. Copy .claude/rules/ directory if provided by the pack
# ---------------------------------------------------------------------------
if [ -d "$PACK_DIR/.claude/rules" ]; then
    mkdir -p ".claude/rules"
    for rule_file in "$PACK_DIR/.claude/rules/"*.md; do
        [ -f "$rule_file" ] || continue
        rule_name=$(basename "$rule_file")
        rule_marker="<!-- Generated by HarnessFlow — do not edit by hand. -->"
        install_generated_file "$rule_file" ".claude/rules/$rule_name" "$rule_marker" "Claude Code rule $rule_name"
    done
fi

# ---------------------------------------------------------------------------
# 6. Install native agent definitions (.claude/agents/, .codex/agents/)
#
# Generated from agents/*.agent.md by sync_agent_definitions.py. A native
# definition puts the role text in the subagent's system prompt instead of the
# spawn prompt, restricts its tools/sandbox, and makes reasoning effort a
# settable field rather than a prompt instruction.
# ---------------------------------------------------------------------------
AGENT_MARKER="Generated by HarnessFlow sync_agent_definitions.py"

install_agent_definitions() {
    local src_dir="$1"
    local dest_dir="$2"
    local ext="$3"
    local label="$4"

    [ -d "$src_dir" ] || return 0
    mkdir -p "$dest_dir"
    for agent_file in "$src_dir"/*."$ext"; do
        [ -f "$agent_file" ] || continue
        install_generated_file "$agent_file" "$dest_dir/$(basename "$agent_file")" \
            "$AGENT_MARKER" "$label"
    done
}

install_agent_definitions "$PACK_DIR/.claude/agents" ".claude/agents" "md" "Claude Code agent definition"
install_agent_definitions "$PACK_DIR/.codex/agents" ".codex/agents" "toml" "Codex agent definition"

# ---------------------------------------------------------------------------
# 7. Ensure repo_info/ folder exists with all canonical files
# ---------------------------------------------------------------------------
REPO_INFO="$PACK_DIR/repo_info"
mkdir -p "$REPO_INFO"

CANONICAL_FILES=(
    "codebase_overview.md"
    "scripts_overview.md"
    "update_logs.md"
    "update_logs_all.md"
    "known_issues.md"
    "update_logs_auto_generated.md"
    "known_issues_auto_generated.md"
    "past_Q&A.md"
    "past_Correctness_Check.md"
)

for f in "${CANONICAL_FILES[@]}"; do
    if [ ! -f "$REPO_INFO/$f" ]; then
        touch "$REPO_INFO/$f"
        echo "Created $REPO_INFO/$f"
    fi
done

echo ""
echo "CLI setup complete."
echo ""
echo "Usage:"
if [ "$HAS_CLAUDE" = true ]; then
    echo "  Claude Code: Run 'claude' from repo root — it discovers CLAUDE.md automatically"
fi
if [ "$HAS_CODEX" = true ]; then
    echo "  Codex:       Run 'codex' from repo root — it discovers AGENTS.md automatically"
fi

# --- Agent Discovery Guidance ---
echo ""
echo "=== Agent Discovery ==="
echo "Source definitions:  .github/HarnessFlow/agents/*.agent.md"
echo "Installed natively:  .claude/agents/*.md  ·  .codex/agents/*.toml"
echo ""
echo "For Claude Code:"
echo "  Spawn workers by their agent type (the lowercase-hyphen name), e.g."
echo "  'focus-analyst' or 'senior-engineer'. The role text is the subagent's"
echo "  system prompt, so it is never re-sent as prompt tokens, and each"
echo "  definition restricts that role's tools."
echo ""
echo "For Codex CLI:"
echo "  AGENTS.md routes to workflow files which reference the same names."
echo "  Project agents in .codex/agents/ load only when the project is trusted;"
echo "  each definition sets its own sandbox_mode."
echo "  Use 'mode: fast' in a prompt to select workflow/token_effective_workflow/."
echo "  If subagent spawning fails, ensure your Codex concurrency settings"
echo "  allow multiple agent workers."
echo ""
echo "After editing any agents/*.agent.md, re-run from the pack root:"
echo "  python3 sync_agent_definitions.py"
echo ""

echo "Next step: Run the initialize workflow to generate repo_info/ memory files."
echo "Done."
