#!/usr/bin/env python3
"""Generate native agent definitions from ``agents/*.agent.md``.

The ``agents/*.agent.md`` files are the single source of truth for every worker
role, but their frontmatter is VS Code Copilot's format. Claude Code and Codex
each read their own native definition format, and a native definition is
cheaper than an ad-hoc prompt spawn: the role text becomes the subagent's
system prompt (never read in-band, never re-sent as prompt tokens), ``tools`` /
``sandbox_mode`` restrict the role, and the reasoning-effort field becomes
settable instead of prompt-enforced.

This script projects each source file into both native formats:

    agents/focus-analyst.agent.md
      -> .claude/agents/focus-analyst.md    (YAML frontmatter + markdown body)
      -> .codex/agents/focus-analyst.toml   (TOML + developer_instructions)

Run it from the pack root whenever an ``agents/*.agent.md`` file changes:

    python3 sync_agent_definitions.py

Outputs are rewritten whole (never patched), and generated files whose source
has disappeared are deleted, so stale hand-edits cannot survive a sync.
``cli_setup.sh`` copies the results into a target repo.
"""

import os
import re
import sys

SRC_DIR = "agents"
SRC_SUFFIX = ".agent.md"
CLAUDE_DIR = os.path.join(".claude", "agents")
CODEX_DIR = os.path.join(".codex", "agents")
MARKER = "Generated by HarnessFlow sync_agent_definitions.py"

# Source `tools:` tokens (VS Code Copilot names) -> Claude Code tool names.
# Every name below survives Claude Code's background-subagent tool filter, so a
# definition resolves to the same tools in the foreground and the background.
CLAUDE_TOOLS = {
    "read": ["Read"],
    "search": ["Grep", "Glob"],
    "listDir": ["Glob"],
    "edit": ["Edit", "Write"],
    "createFile": ["Write"],
    "execute": ["Bash"],
    "runInTerminal": ["Bash"],
    "web": ["WebSearch", "WebFetch"],
    "web/fetch": ["WebSearch", "WebFetch"],
}

# Tokens that mean the role writes to the workspace. Codex has no per-tool
# allowlist — scope is expressed through sandbox_mode instead.
WRITE_TOOLS = {"edit", "createFile", "execute", "runInTerminal"}

# Claude Code effort scale -> Codex's three-level model_reasoning_effort.
CODEX_EFFORT = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "xhigh": "high",
    "max": "high",
}

CLAUDE_DESC_PREFIX = (
    "HarnessFlow worker subagent — spawn only from a HarnessFlow workflow step, "
    "never by autonomous delegation. "
)

def parse_source(path):
    """Split an ``agents/*.agent.md`` file into (frontmatter dict, body)."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read().replace("\r\n", "\n")

    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    if not m:
        raise SystemExit("{}: no YAML frontmatter found.".format(path))
    raw, body = m.group(1), m.group(2).strip()

    front = {}
    for line in raw.split("\n"):
        km = re.match(r"([A-Za-z_-]+):\s*(.*)$", line)
        if km:
            front[km.group(1)] = km.group(2).strip()

    for key in ("name", "description"):
        if not front.get(key):
            raise SystemExit("{}: frontmatter is missing `{}`.".format(path, key))
    effort = front.get("effort")
    if effort and effort not in CODEX_EFFORT:
        raise SystemExit("{}: unknown effort '{}'.".format(path, effort))
    return front, body


def source_tools(path, front):
    """Return the source `tools:` tokens, validated against the tool map."""
    raw = front.get("tools", "")
    tokens = re.findall(r"['\"]([^'\"]+)['\"]", raw)
    if raw.strip() and not tokens:
        raise SystemExit(
            "{}: `tools:` value {!r} parsed to no tokens — quote each tool name.".format(path, raw)
        )
    unknown = [t for t in tokens if t not in CLAUDE_TOOLS]
    if unknown:
        raise SystemExit(
            "{}: unmapped tools {} — add them to CLAUDE_TOOLS/WRITE_TOOLS.".format(path, unknown)
        )
    return tokens


def claude_tools(tokens):
    """Map source tokens to a de-duplicated, order-stable Claude tool list."""
    out = []
    for token in tokens:
        for tool in CLAUDE_TOOLS[token]:
            if tool not in out:
                out.append(tool)
    return out


def yaml_quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_claude(slug, src_name, front, body, tokens):
    lines = ["---", "name: " + slug]
    lines.append("description: " + yaml_quote(CLAUDE_DESC_PREFIX + front["description"]))
    tools = claude_tools(tokens)
    if tools:
        lines.append("tools: " + ", ".join(tools))
    # `inherit` keeps the pack's `subagent_model` rule authoritative: a specific
    # id passed at spawn time overrides the frontmatter, and `inherit`/unset
    # falls through to the main agent's model with no downgrade.
    lines.append("model: inherit")
    if front.get("effort"):
        lines.append("effort: " + front["effort"])
    lines.append("---")
    lines.append("")
    lines.append("<!-- {} from {}/{} — do not edit by hand. -->".format(MARKER, SRC_DIR, src_name))
    lines.append("")
    lines.append(body)
    return "\n".join(lines) + "\n"


def toml_quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_codex(slug, src_name, front, body, tokens):
    if "'''" in body:
        raise SystemExit(
            "{}/{}: body contains ''' — cannot embed in a TOML literal string.".format(
                SRC_DIR, src_name
            )
        )
    sandbox = "workspace-write" if WRITE_TOOLS.intersection(tokens) else "read-only"

    lines = ["# {} from {}/{} — do not edit by hand.".format(MARKER, SRC_DIR, src_name)]
    lines.append("name = " + toml_quote(slug))
    lines.append("description = " + toml_quote(CLAUDE_DESC_PREFIX + front["description"]))
    lines.append("sandbox_mode = " + toml_quote(sandbox))
    effort = front.get("effort")
    if effort:
        if effort not in CODEX_EFFORT:
            raise SystemExit("{}/{}: unknown effort '{}'.".format(SRC_DIR, src_name, effort))
        lines.append("model_reasoning_effort = " + toml_quote(CODEX_EFFORT[effort]))
    lines.append("")
    lines.append("developer_instructions = '''")
    lines.append(body)
    lines.append("'''")
    return "\n".join(lines) + "\n"


def write_if_changed(path, content, written):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            if fh.read() == content:
                written.append((path, "unchanged"))
                return
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    written.append((path, "written"))


def prune_stale(directory, keep, suffix, removed):
    """Delete generated files in `directory` whose source no longer exists."""
    if not os.path.isdir(directory):
        return
    for fname in sorted(os.listdir(directory)):
        if not fname.endswith(suffix) or fname[: -len(suffix)] in keep:
            continue
        path = os.path.join(directory, fname)
        with open(path, encoding="utf-8") as fh:
            if MARKER not in fh.read():
                continue  # hand-written definition — never ours to delete
        os.remove(path)
        removed.append(path)


def main():
    root = os.path.dirname(os.path.abspath(__file__))
    os.chdir(root)
    if not os.path.isdir(SRC_DIR):
        raise SystemExit("{}/ not found next to this script ({}).".format(SRC_DIR, root))

    sources = sorted(f for f in os.listdir(SRC_DIR) if f.endswith(SRC_SUFFIX))
    if not sources:
        raise SystemExit("no *{} files found in {}/.".format(SRC_SUFFIX, SRC_DIR))

    os.makedirs(CLAUDE_DIR, exist_ok=True)
    os.makedirs(CODEX_DIR, exist_ok=True)

    # Parse + render everything into memory first, so any SystemExit fires
    # before the first output file is written.
    written, removed, slugs, outputs = [], [], set(), []
    for src_name in sources:
        slug = src_name[: -len(SRC_SUFFIX)]
        if not re.fullmatch(r"[a-z][a-z-]*", slug):
            raise SystemExit(
                "{}/{}: filename must be lowercase-and-hyphens — it becomes the agent "
                "`name`.".format(SRC_DIR, src_name)
            )
        slugs.add(slug)
        front, body = parse_source(os.path.join(SRC_DIR, src_name))
        tokens = source_tools(os.path.join(SRC_DIR, src_name), front)
        outputs.append(
            (os.path.join(CLAUDE_DIR, slug + ".md"), render_claude(slug, src_name, front, body, tokens))
        )
        outputs.append(
            (os.path.join(CODEX_DIR, slug + ".toml"), render_codex(slug, src_name, front, body, tokens))
        )

    for path, content in outputs:
        write_if_changed(path, content, written)

    prune_stale(CLAUDE_DIR, slugs, ".md", removed)
    prune_stale(CODEX_DIR, slugs, ".toml", removed)

    changed = [p for p, state in written if state == "written"]
    for path in changed:
        print("wrote    {}".format(path))
    for path in removed:
        print("removed  {} (source deleted)".format(path))
    print(
        "{} agent(s) -> {}/ + {}/ · {} file(s) changed, {} removed.".format(
            len(sources), CLAUDE_DIR, CODEX_DIR, len(changed), len(removed)
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
